// <auto-generated />
namespace Events.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MySmallFix1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MySmallFix1));
        
        string IMigrationMetadata.Id
        {
            get { return "201410131831216_MySmallFix1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
